// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cwe_detail.sql

package repository

import (
	"context"
	"time"
)

const createOrUpdateCWEDetail = `-- name: CreateOrUpdateCWEDetail :one
INSERT INTO cwe_details (
  cwe_id,
  title,
  mitigation_phase,
  description,
  last_updated
) VALUES (
  $1, $2, $3, $4, $5
)
ON CONFLICT (cwe_id) DO UPDATE SET
  title = EXCLUDED.title,
  mitigation_phase = EXCLUDED.mitigation_phase,
  description = EXCLUDED.description,
  last_updated = EXCLUDED.last_updated
RETURNING cwe_id, title, mitigation_phase, description, last_updated
`

type CreateOrUpdateCWEDetailParams struct {
	CweID           string    `json:"cwe_id"`
	Title           string    `json:"title"`
	MitigationPhase string    `json:"mitigation_phase"`
	Description     string    `json:"description"`
	LastUpdated     time.Time `json:"last_updated"`
}

func (q *Queries) CreateOrUpdateCWEDetail(ctx context.Context, arg CreateOrUpdateCWEDetailParams) (CweDetail, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateCWEDetail,
		arg.CweID,
		arg.Title,
		arg.MitigationPhase,
		arg.Description,
		arg.LastUpdated,
	)
	var i CweDetail
	err := row.Scan(
		&i.CweID,
		&i.Title,
		&i.MitigationPhase,
		&i.Description,
		&i.LastUpdated,
	)
	return i, err
}
