// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scan.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getScanByID = `-- name: GetScanByID :one
SELECT id, tenant_id, operator_id, host_id, status, started_at, ended_at, created_at, updated_at, protection_score
FROM scans
WHERE id = $1
`

func (q *Queries) GetScanByID(ctx context.Context, id uuid.UUID) (Scan, error) {
	row := q.db.QueryRowContext(ctx, getScanByID, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OperatorID,
		&i.HostID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProtectionScore,
	)
	return i, err
}
