-- name: CreateCVEDetail :one
INSERT INTO cve_details (
    cve_id,
    source_identifier,
    cwe,
    published_date,
    last_modified_date,
    vuln_status,
    cvss_v2_vector,
    cvss_v2_base_score,
    cvss_v2_base_severity,
    cvss_v2_exploitability_score,
    cvss_v2_impact_score,
    cvss_v2_access_vector,
    cvss_v2_access_complexity,
    cvss_v2_authentication,
    cvss_v2_confidentiality_impact,
    cvss_v2_integrity_impact,
    cvss_v2_availability_impact,
    cvss_v30_vector,
    cvss_v30_base_score,
    cvss_v30_base_severity,
    cvss_v30_exploitability_score,
    cvss_v30_impact_score,
    cvss_v30_attack_vector,
    cvss_v30_attack_complexity,
    cvss_v30_privileges_required,
    cvss_v30_user_interaction,
    cvss_v30_scope,
    cvss_v30_confidentiality_impact,
    cvss_v30_integrity_impact,
    cvss_v30_availability_impact,
    cvss_v31_vector,
    cvss_v31_base_score,
    cvss_v31_base_severity,
    cvss_v31_exploitability_score,
    cvss_v31_exploit_code_maturity,
    cvss_v31_impact_score,
    cvss_v31_attack_vector,
    cvss_v31_attack_complexity,
    cvss_v31_privileges_required,
    cvss_v31_user_interaction,
    cvss_v31_scope,
    cvss_v31_confidentiality_impact,
    cvss_v31_integrity_impact,
    cvss_v31_availability_impact,
    epss_score,
    epss_percentile,
    risk_score,
    likelihood,
    evaluator_comment,
    evaluator_impact,
    evaluator_solution,
    cisa_exploit_add,
    cisa_action_due,
    cisa_required_action,
    cisa_vulnerability_name,
    cve_tags,
    nvd_description,
    weaknesses,
    configurations,
    nvd_references,
    vendor_comments
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
    $31, $32, $33, $34, $35, $36, $37, $38, $39, $40,
    $41, $42, $43, $44, $45, $46, $47, $48, $49, $50,
    $51, $52, $53, $54, $55, $56, $57, $58, $59, $60,
    $61
) 
ON CONFLICT (cve_id) DO UPDATE SET
    source_identifier = EXCLUDED.source_identifier,
    cwe = EXCLUDED.cwe,
    published_date = EXCLUDED.published_date,
    last_modified_date = EXCLUDED.last_modified_date,
    vuln_status = EXCLUDED.vuln_status,
    cvss_v2_vector = EXCLUDED.cvss_v2_vector,
    cvss_v2_base_score = EXCLUDED.cvss_v2_base_score,
    cvss_v2_base_severity = EXCLUDED.cvss_v2_base_severity,
    cvss_v2_exploitability_score = EXCLUDED.cvss_v2_exploitability_score,
    cvss_v2_impact_score = EXCLUDED.cvss_v2_impact_score,
    cvss_v2_access_vector = EXCLUDED.cvss_v2_access_vector,
    cvss_v2_access_complexity = EXCLUDED.cvss_v2_access_complexity,
    cvss_v2_authentication = EXCLUDED.cvss_v2_authentication,
    cvss_v2_confidentiality_impact = EXCLUDED.cvss_v2_confidentiality_impact,
    cvss_v2_integrity_impact = EXCLUDED.cvss_v2_integrity_impact,
    cvss_v2_availability_impact = EXCLUDED.cvss_v2_availability_impact,
    cvss_v30_vector = EXCLUDED.cvss_v30_vector,
    cvss_v30_base_score = EXCLUDED.cvss_v30_base_score,
    cvss_v30_base_severity = EXCLUDED.cvss_v30_base_severity,
    cvss_v30_exploitability_score = EXCLUDED.cvss_v30_exploitability_score,
    cvss_v30_impact_score = EXCLUDED.cvss_v30_impact_score,
    cvss_v30_attack_vector = EXCLUDED.cvss_v30_attack_vector,
    cvss_v30_attack_complexity = EXCLUDED.cvss_v30_attack_complexity,
    cvss_v30_privileges_required = EXCLUDED.cvss_v30_privileges_required,
    cvss_v30_user_interaction = EXCLUDED.cvss_v30_user_interaction,
    cvss_v30_scope = EXCLUDED.cvss_v30_scope,
    cvss_v30_confidentiality_impact = EXCLUDED.cvss_v30_confidentiality_impact,
    cvss_v30_integrity_impact = EXCLUDED.cvss_v30_integrity_impact,
    cvss_v30_availability_impact = EXCLUDED.cvss_v30_availability_impact,
    cvss_v31_vector = EXCLUDED.cvss_v31_vector,
    cvss_v31_base_score = EXCLUDED.cvss_v31_base_score,
    cvss_v31_base_severity = EXCLUDED.cvss_v31_base_severity,
    cvss_v31_exploitability_score = EXCLUDED.cvss_v31_exploitability_score,
    cvss_v31_exploit_code_maturity = EXCLUDED.cvss_v31_exploit_code_maturity,
    cvss_v31_impact_score = EXCLUDED.cvss_v31_impact_score,
    cvss_v31_attack_vector = EXCLUDED.cvss_v31_attack_vector,
    cvss_v31_attack_complexity = EXCLUDED.cvss_v31_attack_complexity,
    cvss_v31_privileges_required = EXCLUDED.cvss_v31_privileges_required,
    cvss_v31_user_interaction = EXCLUDED.cvss_v31_user_interaction,
    cvss_v31_scope = EXCLUDED.cvss_v31_scope,
    cvss_v31_confidentiality_impact = EXCLUDED.cvss_v31_confidentiality_impact,
    cvss_v31_integrity_impact = EXCLUDED.cvss_v31_integrity_impact,
    cvss_v31_availability_impact = EXCLUDED.cvss_v31_availability_impact,
    epss_score = EXCLUDED.epss_score,
    epss_percentile = EXCLUDED.epss_percentile,
    risk_score = EXCLUDED.risk_score,
    likelihood = EXCLUDED.likelihood,
    evaluator_comment = EXCLUDED.evaluator_comment,
    evaluator_impact = EXCLUDED.evaluator_impact,
    evaluator_solution = EXCLUDED.evaluator_solution,
    cisa_exploit_add = EXCLUDED.cisa_exploit_add,
    cisa_action_due = EXCLUDED.cisa_action_due,
    cisa_required_action = EXCLUDED.cisa_required_action,
    cisa_vulnerability_name = EXCLUDED.cisa_vulnerability_name,
    cve_tags = EXCLUDED.cve_tags,
    nvd_description = EXCLUDED.nvd_description,
    weaknesses = EXCLUDED.weaknesses,
    configurations = EXCLUDED.configurations,
    nvd_references = EXCLUDED.nvd_references,
    vendor_comments = EXCLUDED.vendor_comments,
    updated_at = NOW()
RETURNING *;
