// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cwe_detail.sql

package db

import (
	"context"
	"time"
)

const createOrUpdateCWEDetail = `-- name: CreateOrUpdateCWEDetail :one
INSERT INTO cwe_details (
    cwe_id,
    title,
    description,
    last_updated
) VALUES (
  $1, $2, $3, $4
) ON CONFLICT (cwe_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  last_updated = EXCLUDED.last_updated
RETURNING cwe_id, title, description, last_updated, created_at
`

type CreateOrUpdateCWEDetailParams struct {
	CweID       string    `json:"cwe_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	LastUpdated time.Time `json:"last_updated"`
}

func (q *Queries) CreateOrUpdateCWEDetail(ctx context.Context, arg CreateOrUpdateCWEDetailParams) (CweDetail, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateCWEDetail,
		arg.CweID,
		arg.Title,
		arg.Description,
		arg.LastUpdated,
	)
	var i CweDetail
	err := row.Scan(
		&i.CweID,
		&i.Title,
		&i.Description,
		&i.LastUpdated,
		&i.CreatedAt,
	)
	return i, err
}
