// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cwe_detail.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createOrUpdateCWEDetail = `-- name: CreateOrUpdateCWEDetail :one
INSERT INTO cwe_details (
    cwe_id,
    title,
    description,
    last_updated
) VALUES (
  $1, $2, $3, $4
) ON CONFLICT (cwe_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  last_updated = EXCLUDED.last_updated
RETURNING cwe_id, title, description, last_updated, created_at
`

type CreateOrUpdateCWEDetailParams struct {
	CweID       string    `json:"cwe_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	LastUpdated time.Time `json:"last_updated"`
}

func (q *Queries) CreateOrUpdateCWEDetail(ctx context.Context, arg CreateOrUpdateCWEDetailParams) (CweDetail, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateCWEDetail,
		arg.CweID,
		arg.Title,
		arg.Description,
		arg.LastUpdated,
	)
	var i CweDetail
	err := row.Scan(
		&i.CweID,
		&i.Title,
		&i.Description,
		&i.LastUpdated,
		&i.CreatedAt,
	)
	return i, err
}

const getCWEDetailWithMitigationsByID = `-- name: GetCWEDetailWithMitigationsByID :many
SELECT
  cd.cwe_id,
  cd.title,
  cd.description,
  cm.id AS mitigation_id,
  cm.mitigation_id AS mitigation_code,
  cm.phase,
  cm.description AS mitigation_description,
  cm.effectiveness,
  cm.effectiveness_notes
FROM cwe_details cd
LEFT JOIN cwe_mitigations cm ON cd.cwe_id = cm.cwe_id
WHERE cd.cwe_id = $1
`

type GetCWEDetailWithMitigationsByIDRow struct {
	CweID                 string         `json:"cwe_id"`
	Title                 string         `json:"title"`
	Description           string         `json:"description"`
	MitigationID          sql.NullInt32  `json:"mitigation_id"`
	MitigationCode        sql.NullString `json:"mitigation_code"`
	Phase                 sql.NullString `json:"phase"`
	MitigationDescription sql.NullString `json:"mitigation_description"`
	Effectiveness         sql.NullString `json:"effectiveness"`
	EffectivenessNotes    sql.NullString `json:"effectiveness_notes"`
}

func (q *Queries) GetCWEDetailWithMitigationsByID(ctx context.Context, cweID string) ([]GetCWEDetailWithMitigationsByIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getCWEDetailWithMitigationsByID, cweID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCWEDetailWithMitigationsByIDRow
	for rows.Next() {
		var i GetCWEDetailWithMitigationsByIDRow
		if err := rows.Scan(
			&i.CweID,
			&i.Title,
			&i.Description,
			&i.MitigationID,
			&i.MitigationCode,
			&i.Phase,
			&i.MitigationDescription,
			&i.Effectiveness,
			&i.EffectivenessNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
