// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: wasc_detail.sql

package db

import (
	"context"
	"time"
)

const createOrUpdateWASCDetail = `-- name: CreateOrUpdateWASCDetail :one
INSERT INTO wasc_details (
    wasc_id,
    title,
    description,
    last_updated
) VALUES (
  $1, $2, $3, $4
) ON CONFLICT (wasc_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  last_updated = EXCLUDED.last_updated
RETURNING wasc_id, title, description, last_updated
`

type CreateOrUpdateWASCDetailParams struct {
	WascID      string    `json:"wasc_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	LastUpdated time.Time `json:"last_updated"`
}

func (q *Queries) CreateOrUpdateWASCDetail(ctx context.Context, arg CreateOrUpdateWASCDetailParams) (WascDetail, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateWASCDetail,
		arg.WascID,
		arg.Title,
		arg.Description,
		arg.LastUpdated,
	)
	var i WascDetail
	err := row.Scan(
		&i.WascID,
		&i.Title,
		&i.Description,
		&i.LastUpdated,
	)
	return i, err
}
